services:

  # === FLASK APPS (Separate Network) ===
  flask_app1:
    build: ./FlaskWeb/WebApp1
    container_name: flask_web_app1
    ports:
      - "5001:5000"
    networks:
      - flask_net
    depends_on:
      collector:
        condition: service_started

  flask_app2:
    build: ./FlaskWeb/WebApp2
    container_name: flask_web_app2
    ports:
      - "5002:5000"
    networks:
      - flask_net
    depends_on:
      collector:
        condition: service_started

# === SNOWPLOW TRACKER FRONTEND ===
  tracker-frontend:
    container_name: snow-tracker-frontend
    build: ./FlaskWeb/DataTracker/
    ports:
      - 3000:80
    networks:
      - flask_net

networks:
  flask_net:
    # driver: bridge