collector {
  interface = "0.0.0.0"
  port = 8080

  p3p {
    policyRef = "/w3c/p3p.xml"
    CP = "NOI DSP COR NID PSA OUR IND COM NAV STA"
  }

  cookie {
    enabled = true
    expiration = 365 days
    name = sp
    domains = []
    secure = false
    httpOnly = false
  }

  sink {
    enabled = kafka
    kafka {
      brokers = "kafka:9092"
      topicName = "snowplow-raw"
    }
  }

  buffer {
    byteLimit = 100000
    recordLimit = 500
    timeLimit = 10000
  }

  paths {
    /health = GET
  }

  prometheusMetrics {
    enabled = false
  }
}
