enrich {
  streams {
    in.raw = "snowplow-raw"
    out.enriched = "snowplow-enriched"
    out.bad = "snowplow-bad"

    sourceSink {
      enabled = kafka
      kafka {
        brokers = "kafka:9092"
      }
    }

    buffer {
      byteLimit = 100000
      recordLimit = 500
      timeLimit = 10000
    }
  }

  monitoring {
    snowplow {
      collectorUri = ""
      appId = ""
      method = get
    }
  }

  telemetry {
    disable = true
  }
}
